### ISSUE TITLE
utf8 自动转成 gbk 了

### ISSUE THREAD

**Issue by chenyitian** [lypeer/Matchmaker#1]
windows 7 64, intellij idea 2016.3 rc

**Comment by lypeer** [comment]
什么意思，不懂。。。

**Comment by lypeer** [comment]
@chenyitian

**Comment by chenyitian** [comment]
我在 intellij idea 里面编辑带有中文的 utf-8 编码的 js，右键->Generate->Match make，js 会自动转成 GBK 编码。刚才还发现一个bug，在不同目录下面同时有多个名为 index.js 的文件，编辑 index/index.js，match maker 会提示“There exists more than one file in your project called index.wxml”，而没有匹配到index/index.wxml，应该是可以找到对应的 wxml 的吧？

**Comment by Niofh** [comment]
@lypeer webstorm现在可以了吗
